############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Projects"
url = "/projects"
weight = 2

[[main]]
name = "News"
url = "/news"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 4


[[main]]
weight = 5
name = "Divisions"

[[main]]
parent = "Divisions"
name = "Design"
url = "/design-division"

[[main]]
parent = "Divisions"
name = "Motors"
url = "/motors-division"

[[main]]
parent = "Divisions"
name = "Systems"
url = "/systems-division"


# footer menu
[[footer]]
name = "Contact"
url = "/contact"
weight = 1

[[footer]]
name = "Cookie Policy"
url = "/cookie-policy"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
